name = "cw721-dapp"

gas_price = '2.5ueaura'
gas_adjustment = 1.3
account_prefix = 'aura'
derivation_path = '''m/44'/118'/0'/0/0'''

[networks.testnet]
chain_id = 'serenity-testnet-001'
network_variant = 'Shared'
grpc_endpoint = 'https://grpc.serenity.aura.network:9092'
rpc_endpoint = 'https://rpc.serenity.aura.network'

[networks.euphoria]
chain_id = 'euphoria-2'
network_variant = 'Shared'
grpc_endpoint = 'http://grpc.euphoria.aura.network:9090'
rpc_endpoint = 'https://rpc.euphoria.aura.network'

[accounts.signer]
mnemonic = 'caution toy sick fresh infant ghost loud afford stable kite nature uncover thought nice buddy strategy awful lab rapid session mimic jazz day square'